config/routes.rb
Rails.application.routes.draw do
   root to: 'public/homes#top'


   get 'customers/my_page' => 'public/customers#show'
   get 'customers/edit' => 'public/customers#edit'
   patch 'customers' => 'public/customers#update'
   get 'customers/confirm' => 'public/customers#confirm'
   patch 'customers/withdraw' => 'public/customers#withdraw'
   delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'

   get 'orders/thanks' => 'public/orders#thanks'
   post 'orders/confirm' =>'public/orders#confirm'

   get 'about' => 'public/homes#about'

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  resources :items,only: [:index,:show]
end

scope module: :public do
  resources :cart_items,only:[:index,:update,:destroy,:create]
end

scope module: :public do
  resources :orders, only:[:new,:index,:create,:show]
end

scope module: :public do
  resources :addresses, except:[:show]
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

namespace :admin do
  resources :items
end

namespace :admin do
  resources :genres,only: [:new,:index,:create,:edit,:update]
end

namespace :admin do
  resources :customers,only: [:index,:show,:edit,:update]
end

namespace :admin do
  resources :orders,only: [:show,:update,:index]
end

namespace :admin do
  resources :order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to:customer

def address_display
    self.postal_code + self.name + self.address
end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to:item
    belongs_to:customer
    has_one_attached :image
    has_many :item_total_price
    validates :amount, presence: true

    def item_total_price
        cart_item.price*cart_item.amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :addresses,dependent: :destroy

 def active_for_authentication?
   super && self.is_active
 end




end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to:genre,optional: true
    has_many:cart_items,dependent: :destroy
    has_many:order_details, dependent: :destroy
    has_one_attached :image

    def with_tax_price
        (price*1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many:order_details,dependent: :destroy
    belongs_to:customer
    has_one_attached :image
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { waiting_payment: 0, payment_confirm: 1, making:2, before_sent: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to:order
    belongs_to:item
    enum making_status: {not_make:0, make_wait:1, make_now:2, make_done:3}


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

    def index
        @customers = Customer.all

    end


    def edit
        @customer = Customer.find(params[:id])
    end

    def update
        customer = Customer.find(params[:id])
        customer.update(customer_params)
        redirect_to admin_customer_path(customer.id)
    end

    def show
      @customer = Customer.find(params[:id])
    end

    def customer_params
    params.require(:customer).permit(:last_name,:first_name,:postal_code,:address,:last_name_kana,:first_name_kana,:telephone_number,:email,:is_active)
    end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

     def new
         @genre = Genre.new
     end

     def create
          genre = Genre.new(genre_params)
          genre.save
          redirect_to '/admin/genres'
     end

     def index
          @genre = Genre.new
          @genres = Genre.all
     end

     def edit
          @genre = Genre.find(params[:id])
     end

     def update
          genre =Genre.find(params[:id])
          genre.update(genre_params)
          redirect_to '/admin/genres'
     end

     private

     def genre_params
          params.require(:genre).permit(:name)
     end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
def top
    @orders = Order.all
end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

    def new
        @item =Item.new
        @genre =Genre.all
    end

    def index
        @items = Item.all
        @genres = Genre.all
    end

    def create
        item = Item.new(item_params)
        item.save!
        redirect_to admin_item_path(item.id)
    end

    def show
        @item = Item.find(params[:id])
        @genre = @item.genre.name
    end



    def edit
        @item = Item.find(params[:id])
        @genre = Genre.all
    end

    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to admin_item_path(item.id)
    end

    private

    def item_params
        params.require(:item).permit(:name,:introduction,:genre_id,:price,:is_active,:image)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    def show
        @order = Order.find(params[:id])
    end

    def update
        order = Order.find(params[:id])
        order.update(order_params)
        if params[:order][:status] == "payment_confirm"
          order.order_details.each do |order_detail|
          order_detail.making_status = "make_wait"
          order_detail.save
          end
        end
        redirect_to admin_order_path(order.id)
    end

    def index
      @orders = Order.all
      @order_details =OrderDetail.all
    end


private

 def order_params
     params.require(:order).permit(:last_name,:first_name,:postal_code,:address,:payment_method,:status,:amount)
 end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters,if: :devise_controller?
helper_method :current_cart

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:last_name,:first_name,:last_name_kana,:first_name_kana,:address,:telephone_number,:postal_code])
end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<%= render'public/homes/header',homes: @homes %>


<h2><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>

<%= form_with model:@customer,url:admin_customer_path(@customer.id),method: :patch do |f| %>
<div class="customer-edit">
 <div class ="customer-edit-koumoku">
  <p>会員ID</p>
  <p>氏名</p>
  <p>フリガナ</p>
  <p>郵便番号</p>
  <p>住所</p>
  <p>電話番号</p>
  <p>メールアドレス</p>
  <p>会員ステータス</p>
 </div>

 <div class ="customer-edit-info">
  <p><%= @customer_id %></p>
  <p><%= f.text_field:last_name %><%= f.text_field:first_name %></p>
  <p><%= f.text_field:last_name_kana %><%= f.text_field:first_name_kana %></p>
  <p><%= f.text_field:postal_code %></p>
  <p><%= f.text_field:address %></p>
  <p><%= f.text_field:telephone_number %></p>
  <p><%= f.text_field:email %></p>
  <p><%= f.radio_button:is_active,:true %><%= f.label:"有効" %><%= f.radio_button:is_active,:false %><%= f.label:"退会" %></p>
 </div>
</div>

<div class ="customer-edit-action">
<%= f.submit '変更を保存',class:"btn btn-success" %>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>
<h2>会員一覧画面</h2>
  <table>

   <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
   </tr>
   <% @customers.each do |customer| %>
   <tr>
    <td><%= customer.id %></td>
    <td><%= link_to customer.last_name + customer.first_name,admin_customer_path(customer.id) %></td>
    <td><%= customer.email %></td>
    <td><% if customer.is_active == true %>
     <a class ="text-success">有効</a>
     <% else %>
     <a class ="text-muted">退会</a>
     <% end %></td>
   </tr>
   　 <% end %>
  </table>

app/views/admin/customers/show.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>

   <h2> <%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    <table class ="customer-info">
     <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
     </tr>

     <tr>
      <td>氏名</td>
      <td><%= @customer.last_name + @customer.first_name %></td>
     </tr>

     <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
     </tr>

     <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
     </tr>

     <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
     </tr>

     <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
     </tr>

     <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
     </tr>

     <tr>
      <td>会員ステータス</td>
      <td><% if @customer.is_active == true %>
      　　<a class ="text-success">有効</a>
         <% else %>
         <a class ="text-muted">退会</a>
         <% end %></td>
     </tr>
    </table>
<div class ="customer-show-action">
 <%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
</div>