config/routes.rb
Rails.application.routes.draw do
   root to: 'public/homes#top'


   get 'customers/my_page' => 'public/customers#show'
   get 'customers/edit' => 'public/customers#edit'
   patch 'customers' => 'public/customers#update'
   get 'customers/confirm' => 'public/customers#confirm'
   patch 'customers/withdraw' => 'public/customers#withdraw'
   delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'

   get 'orders/thanks' => 'public/orders#thanks'
   post 'orders/confirm' =>'public/orders#confirm'

   get 'about' => 'public/homes#about'

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  resources :items,only: [:index,:show]
end

scope module: :public do
  resources :cart_items,only:[:index,:update,:destroy,:create]
end

scope module: :public do
  resources :orders, only:[:new,:index,:create,:show]
end

scope module: :public do
  resources :addresses, except:[:show]
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

namespace :admin do
  resources :items
end

namespace :admin do
  resources :genres,only: [:new,:index,:create,:edit,:update]
end

namespace :admin do
  resources :customers,only: [:index,:show,:edit,:update]
end

namespace :admin do
  resources :orders,only: [:show,:update,:index]
end

namespace :admin do
  resources :order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to:customer

def address_display
    self.postal_code + self.name + self.address
end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to:item
    belongs_to:customer
    has_one_attached :image
    has_many :item_total_price
    validates :amount, presence: true

    def item_total_price
        cart_item.price*cart_item.amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :addresses,dependent: :destroy

 def active_for_authentication?
   super && self.is_active
 end




end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to:genre,optional: true
    has_many:cart_items,dependent: :destroy
    has_many:order_details, dependent: :destroy
    has_one_attached :image

    def with_tax_price
        (price*1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many:order_details,dependent: :destroy
    belongs_to:customer
    has_one_attached :image
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { waiting_payment: 0, payment_confirm: 1, making:2, before_sent: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to:order
    belongs_to:item
    enum making_status: {not_make:0, make_wait:1, make_now:2, make_done:3}


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

     def new
         @genre = Genre.new
     end

     def create
          genre = Genre.new(genre_params)
          genre.save
          redirect_to '/admin/genres'
     end

     def index
          @genre = Genre.new
          @genres = Genre.all
     end

     def edit
          @genre = Genre.find(params[:id])
     end

     def update
          genre =Genre.find(params[:id])
          genre.update(genre_params)
          redirect_to '/admin/genres'
     end

     private

     def genre_params
          params.require(:genre).permit(:name)
     end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
def top
    @orders = Order.all
end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

    def new
        @item =Item.new
        @genre =Genre.all
    end

    def index
        @items = Item.all
        @genres = Genre.all
    end

    def create
        item = Item.new(item_params)
        item.save!
        redirect_to admin_item_path(item.id)
    end

    def show
        @item = Item.find(params[:id])
        @genre = @item.genre.name
    end



    def edit
        @item = Item.find(params[:id])
        @genre = Genre.all
    end

    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to admin_item_path(item.id)
    end

    private

    def item_params
        params.require(:item).permit(:name,:introduction,:genre_id,:price,:is_active,:image)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    def show
        @order = Order.find(params[:id])
    end

    def update
        order = Order.find(params[:id])
        order.update(order_params)
        if params[:order][:status] == "payment_confirm"
          order.order_details.each do |order_detail|
          order_detail.making_status = "make_wait"
          order_detail.save
          end
        end
        redirect_to admin_order_path(order.id)
    end

    def index
      @orders = Order.all
      @order_details =OrderDetail.all
    end


private

 def order_params
     params.require(:order).permit(:last_name,:first_name,:postal_code,:address,:payment_method,:status,:amount)
 end


end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
 def after_sign_out_path_for(resource)
   new_admin_session_path
 end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters,if: :devise_controller?
helper_method :current_cart

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:last_name,:first_name,:last_name_kana,:first_name_kana,:address,:telephone_number,:postal_code])
end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>

<h3>ジャンル編集</h3>
  <%= form_with model:@genre,url:admin_genre_path,method: :patch do |f| %>
<a>ジャンル名 <%= f.text_field :name %> <%= f.submit '変更を保存',class:"btn btn-success" %> <% end %></a>

app/views/admin/genres/index.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>

<h2>ジャンル一覧・追加</h2>
  <%= form_with model: @genre,url:admin_genres_path do |f| %>
 <div class ="genre-new">
  ジャンル名<%= f.text_field:name %><%= f.submit '新規登録',class:"btn btn-success" %>
  <% end %>
 </div>

<table class="genre-table">
 <tr>
  <th>ジャンル</th>
  <th></th>
 </tr>

 <% @genres.each do |genre| %>
 <tr>
  <td><%= genre.name %></td>
  <td><%= link_to '編集する',edit_admin_genre_path(genre.id),class:"btn btn-success" %></td>
 </tr>
 <% end %>

</table>

app/views/admin/items/edit.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>

<h2>商品編集</h2>
  <%= form_with model:@item,url:admin_item_path(@item.id),method: :patch do |f| %>

  <div class ="item-edit">
　 <p>商品画像
　  <%= f.file_field :image,accept:"image/*" %>
　 </p>

　<p>商品名
　  <%= f.text_field :name %>
　</p>

　<p>商品説明
　  <%= f.text_field :introduction %>
　</p>

　<p>ジャンル
　  <%= f.collection_select(:genre_id,@genre,:id,:name, include_blank: '---選択してください---' ) %>
　</p>

　<p>税抜価格
　  <%= f.text_field :price %>
　</p>

　<p>販売ステータス
　  <%= f.radio_button:is_active,:true %><%= f.label:"販売中" %><%= f.radio_button:is_active,:false %><%= f.label:"販売休止中" %>
　  <%= f.submit "変更を保存",class:"btn btn-success" %>
　</p>

<% end %>
</div>

app/views/admin/items/index.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>
<h2>商品一覧</h2>
<a class ="item-new"><%= link_to"商品新規登録","/admin/items/new" %></a>

  <table>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name,"/admin/items/#{item.id}" %></td>
      <td><%= item.price.to_s(:delimited) %></td>
      <td><%= item.genre.name %></td>
      <td><% if item.is_active == true %>
            <p class ="text-success">販売中</p>
          <% else %>
            <p class ="text-muted">販売停止中</p>
          <% end %></td>
    </tr>
    <% end %>
  </table>

app/views/admin/items/new.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>

<h2>商品新規登録</h2>
<div class ="admin_item_new">
 <%= form_with model:@item,url:admin_items_path do |f| %>

  商品画像 <%= f.file_field :image,accept:"image/*" %><br>

  商品名 <%= f.text_field:name %><br>

  商品説明 <%= f.text_field:introduction %><br>

  ジャンル <%= f.collection_select(:genre_id,@genre,:id,:name, include_blank: '---選択してください---' ) %><br>

  税抜価格 <%= f.text_field:price %>円<br>

  販売ステータス <%= f.radio_button:is_active,:true %><%= f.label:"販売中" %><%= f.radio_button:is_active,:false %><%= f.label:"販売休止中" %><br>

  <%= f.submit '新規登録',class:"btn btn-success" %>
<% end %>
</div>

app/views/admin/items/show.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>
<h2>商品詳細</h2>
<div class = "admin-item-show">
 <div class ="item-show-img">
 <%= image_tag @item.image,size:"300x200" %>
 </div>

<div class = "item-show">
 <a>商品名
　<%= @item.name %><br>
 </a>

 <a>商品説明
　<%= @item.introduction %><br>
 </a>

 <a>ジャンル
　<%= @genre %><br>
 </a>

 <a>税込価格（税抜価格）
　<%= (@item.price*1.1).floor.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円<br>
 </a>

 <a>販売ステータス
　<% if @item.is_active == true %>
 　<p class ="text-success">販売中</p>
  <% else %>
   <p class ="text-muted">販売停止中</p><br>
  <% end %>
　<a><%= link_to "編集する",edit_admin_item_path(@item.id),class:"btn btn-success" %></a>
 </div>
</div>

app/views/admin/orders/index.html.erb
<h2>注文履歴一覧</h2>
 <h3>購入日時</h3>
 <h3>購入者</h3>
 <h3>注文個数</h3>
 <h3>注文ステータス</h3>

 

app/views/admin/orders/show.html.erb
<%= render 'admin/homes/admin_header',homes: @homes %>

<%= form_with model:@order,url:admin_order_path,method: :patch do |f| %>
<h2>注文履歴詳細</h2>
  <div class ="admin-order-show">
   <div class ="admin-order-koumoku">
    <p>購入者</p>
    <p>注文日</p>
    <p>配送先</p>
    <p>支払方法</p>
    <p>注文ステータス</p>
   </div>

   <div class ="admin-order-info">
    <p><%= @order.customer.last_name + @order.customer.first_name %></p>
    <p><%= @order.created_at.strftime('%Y/%m/%d') %></p>
    <p>〒<%= @order.postal_code %>
         <%= @order.address %>
         <%= @order.name %></p>
    <p><%= @order.payment_method_i18n %></p>
    <p><%= f.select :status,Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
       <%= f.submit "更新",class:"btn btn-success" %>
       <% end %></p>
    </div>
  </div>


<table>
  <tr>
   <th>商品名</th>
   <th>単価（税込）</th>
   <th>数量</th>
   <th>小計</th>
   <th>製作ステータス</th>
  </tr>

 <% @total_price = 0 %>
 <% @order.order_details.each do |order_detail| %>
 <%= form_with model:order_detail,url:admin_order_detail_path(order_id: @order.id, id: order_detail.id),method: :patch do |f| %>
<tr>
  <td><%= order_detail.item.name %></td>
  <td><%= (order_detail.price*1.1).floor.to_s(:delimited) %></td>
  <td><%= order_detail.amount %></td>
  <td><%= ((order_detail.price*1.1)*order_detail.amount).floor.to_s(:delimited) %></td>
  <td><%= f.select :making_status,OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"),k]} %>
  <%= f.submit "更新",class:"btn btn-success" %>
 <% end %></td>
</tr>
<% @total_price += ((order_detail.price*1.1)*order_detail.amount).floor %>
<% end %>
</table>


   <div class ="order-total-price">
     <p>商品合計<%= @total_price %>円 </p>
     <p>送料 <%= @postage= 800 %>円</p>
     <p>請求金額合計<%= @postage + @total_price %>円</p>
   </div>