config/routes.rb
Rails.application.routes.draw do
   root to: 'public/homes#top'


   get 'customers/my_page' => 'public/customers#show'
   get 'customers/edit' => 'public/customers#edit'
   patch 'customers' => 'public/customers#update'
   get 'customers/confirm' => 'public/customers#confirm'
   patch 'customers/withdraw' => 'public/customers#withdraw'
   delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'

   get 'orders/thanks' => 'public/orders#thanks'
   post 'orders/confirm' =>'public/orders#confirm'

   get 'about' => 'public/homes#about'

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  resources :items,only: [:index,:show]
end

scope module: :public do
  resources :cart_items,only:[:index,:update,:destroy,:create]
end

scope module: :public do
  resources :orders, only:[:new,:index,:create,:show]
end

scope module: :public do
  resources :addresses, except:[:show]
end

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

get 'admin' => 'admin/homes#top'

namespace :admin do
  resources :items
end

namespace :admin do
  resources :genres,only: [:new,:index,:create,:edit,:update]
end

namespace :admin do
  resources :customers,only: [:index,:show,:edit,:update]
end

namespace :admin do
  resources :orders,only: [:show,:update,:index]
end

namespace :admin do
  resources :order_details,only: [:update]
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to:customer

def address_display
    self.postal_code + self.name + self.address
end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to:item
    belongs_to:customer
    has_one_attached :image
    has_many :item_total_price
    validates :amount, presence: true

    def item_total_price
        cart_item.price*cart_item.amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :addresses,dependent: :destroy

 def active_for_authentication?
   super && self.is_active
 end




end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to:genre,optional: true
    has_many:cart_items,dependent: :destroy
    has_many:order_details, dependent: :destroy
    has_one_attached :image

    def with_tax_price
        (price*1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many:order_details,dependent: :destroy
    belongs_to:customer
    has_one_attached :image
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { waiting_payment: 0, payment_confirm: 1, making:2, before_sent: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to:order
    belongs_to:item
    enum making_status: {not_make:0, make_wait:1, make_now:2, make_done:3}


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

     def new
         @genre = Genre.new
     end

     def create
          genre = Genre.new(genre_params)
          genre.save
          redirect_to '/admin/genres'
     end

     def index
          @genre = Genre.new
          @genres = Genre.all
     end

     def edit
          @genre = Genre.find(params[:id])
     end

     def update
          genre =Genre.find(params[:id])
          genre.update(genre_params)
          redirect_to '/admin/genres'
     end

     private

     def genre_params
          params.require(:genre).permit(:name)
     end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
def top
    @orders = Order.all
end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

    def new
        @item =Item.new
        @genre =Genre.all
    end

    def index
        @items = Item.all
        @genres = Genre.all
    end

    def create
        item = Item.new(item_params)
        item.save!
        redirect_to admin_item_path(item.id)
    end

    def show
        @item = Item.find(params[:id])
        @genre = @item.genre.name
    end



    def edit
        @item = Item.find(params[:id])
        @genre = Genre.all
    end

    def update
        item = Item.find(params[:id])
        item.update(item_params)
        redirect_to admin_item_path(item.id)
    end

    private

    def item_params
        params.require(:item).permit(:name,:introduction,:genre_id,:price,:is_active,:image)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    def show
        @order = Order.find(params[:id])
    end

    def update
        order = Order.find(params[:id])
        order.update(order_params)
        if params[:order][:status] == "payment_confirm"
          order.order_details.each do |order_detail|
          order_detail.making_status = "make_wait"
          order_detail.save
          end
        end
        redirect_to admin_order_path(order.id)
    end

    def index
      @orders = Order.all
      @order_details =OrderDetail.all
    end


private

 def order_params
     params.require(:order).permit(:last_name,:first_name,:postal_code,:address,:payment_method,:status,:amount)
 end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters,if: :devise_controller?
helper_method :current_cart

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:last_name,:first_name,:last_name_kana,:first_name_kana,:address,:telephone_number,:postal_code])
end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/_admin_header.html.erb
<div class="container">
  <header>
   <div class = "row border-bottom">
    <h3 class="col-xl-5 font-italic text-left">
     <%= image_tag('nagano_cake.jpeg') %>
    </h3>

    <div class="col-xl-7 text-right font-italic">
      <a class= "d-inline-block m-4">
       <%= link_to "Items",admin_items_path %>
      </a>
      <a class="d-inline-block m-4">
       <%= link_to "Customers",admin_customers_path %>
      </a>
      <a class="d-inline-block m-4">
       <%= link_to "Orders",admin_path %>
      </a>
      <a class="d-inline-block m-4">
       <%= link_to "Genres",admin_genres_path  %>
      </a>
       <a class ="d-inline-block m-4">
        <%= link_to "Log out",destroy_admin_session_path,method: :delete %>
       </a>
    </header>
   </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <header>
   <div class = "row border-bottom">
    <h3 class="col-xl-5 font-italic text-left">
     <%= image_tag('nagano_cake.jpeg') %>
    </h3>
    <div class="col-xl-7 text-right font-italic">
      <a class= "d-inline-block m-4">
       <%= link_to "About",about_path %>
      </a>
      <a class="d-inline-block m-4">
       <%= link_to "Items",items_path %>
      </a>
      <a class="d-inline-block m-4">
       <%= link_to"Sign in",new_customer_registration_path %>
      </a>
      <a class="d-inline-block m-4">
       <%= link_to "Log in",new_admin_session_path %>
      </a>
    </header>
   </div>
  </div>
</div>

<h2>注文履歴一覧</h2>
<table>
  <tr>
    <th>購入日時</th>
    <th>購入者</th>
    <th>注文個数</th>
    <th>注文ステータス</th>
  </tr>
  <% @orders.each do |order| %>
  <% @total_amount = 0 %>
   <tr>
      <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M'),admin_order_path(order.id) %></td>
      <td><%= order.customer.last_name + order.customer.first_name %></td>
      <td><% order.order_details.each do |order_detail| %>
          <% @total_amount += order_detail.amount %>
          <% end %>
          <%= @total_amount %></td>
      <td> <%= order.status_i18n  %></td>
    </tr>
  <% end %>
</table>